[package]
name = "fmin"
version = "0.3.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
crossterm = "0.23.2"
chrono = "0.4.19"
byte-unit = "4.0.14"
log = "0.4.20"
